import { type NextPage } from "next";
import Head from "next/head";
import SearchBox from "../components/SearchBox";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const search = api.search.default.useQuery();

  return (
    <>
      <Head>
        <title>Search For Answers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header>
          <h1 className="text-2xl font-bold text-white">Search For Answers</h1>
        </header>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {search.isFetched && search.data ? (
            <SearchBox suggestions={search.data.suggestions} />
          ) : (
            <span>Loading</span>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
